version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8876:80
    depends_on:
      - app
    container_name: demo_laravel

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: demo_app
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: mydb
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    container_name: demo_db
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgAdmin
      ports:
       - 5050:80
      depends_on:
          - db
      environment:
          PGADMIN_DEFAULT_EMAIL: kerob.job@gmail.com
          PGADMIN_DEFAULT_PASSWORD: root

